# Generated by Django 3.2.6 on 2021-08-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20210826_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ville',
            field=models.CharField(default='', max_length=100, verbose_name='Ville'),
        ),
    ]
