# Generated by Django 3.2.6 on 2021-09-02 20:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_order_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('tel', models.CharField(default='', max_length=100, verbose_name='Telephone')),
                ('adresse', models.CharField(default='', max_length=1000, verbose_name='Adresse')),
                ('ville', models.CharField(default='', max_length=100, verbose_name='Ville')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='commande',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='camera.commande', verbose_name='commande'),
        ),
    ]
