# Generated by Django 3.2.6 on 2021-09-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_auto_20210902_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nbre',
            field=models.IntegerField(default=0, verbose_name='Nbre Photos'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
