# Generated by Django 3.2.6 on 2021-09-18 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_auto_20210905_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='ville',
        ),
        migrations.AddField(
            model_name='commande',
            name='typec',
            field=models.CharField(default='', max_length=100, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('tel', models.CharField(default='', max_length=100, verbose_name='Telephone')),
                ('adresse', models.CharField(default='', max_length=1000, verbose_name='Adresse')),
                ('ville', models.CharField(default='', max_length=100, verbose_name='Ville')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete', models.BooleanField(default=False)),
                ('commande', models.ManyToManyField(default='', to='camera.Commande', verbose_name='commande')),
            ],
        ),
    ]
