# Generated by Django 3.2.6 on 2021-09-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_auto_20210918_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='listcommande',
            field=models.CharField(default='', max_length=1000, verbose_name='listcommande'),
        ),
    ]
